name: route
description: A Flutter app to chat with LLMs offered by OpenRouter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.4
  auris: ^0.2.0
  record: ^7.1.0
  audioplayers: ^6.7.1
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
